### ISSUE TITLE
Use English language in source code

### ISSUE THREAD

**Issue by urbalazs** [joserribeiro26/OTRS-UpdateParent#1]
Hi @joserribeiro26,

I would like to translate this module into Hungarian, but I don't speak Portuguese. Can you replace all the strings in the source code with English ones, and move the Portuguese strings into Kernel/Language/pt_BR_UpdateParent.pm ?
Then I can make a pull request with the Hungarian language file.

Regards,
Balázs

**Comment by joserribeiro26** [comment]
I will do that.
